### PR TITLE
Add PHP 5.4 support

### PR DESCRIPTION
**Pull request by jtojnar**
I really like this library and would like to use it in [selfoss](https://github.com/SSilence/selfoss) RSS reader. Unfortunately, we target PHP 5.4 since it is still [supported](https://wiki.debian.org/PHP#Available_versions) by Debian until [May 2018](https://wiki.debian.org/LTS), which many of our users run on shared web hosts.

Luckily, the library seems to work so we only need to de-bump constraints in `composer.json`. I also added linter to catch accidental uses of unsupported syntax.

Could you please consider supporting 5.4 for one more year?

Edit: Hmm, it looks like `imagescale` is not supported on PHP 5.4 in addition to HHVM. Resize could be taken from this MIT library: https://github.com/claviska/SimpleImage/blob/3158283f02712928e51ff6e2f0bfcfeb31b48e66/src/claviska/SimpleImage.php#L756

### CODE REVIEW

**Comment by lordelph** [comment]
Given 5.4 is 2 years past its end of life, I wouldn't want to burden this relatively new package with having to support it. 

However, here is one approach we could take

* get this pull request passing with some kind of polyfill for imagescale
* branch current master as v2.0, so that v2.0 only supports current php releases
* then have a second branch of master as v1.1, to which this pull request is applied

That way, anyone needing support for old php versions can specify that in their composer.json

How does that sound?

**Comment by jtojnar** [comment]
That would work for us. I could help backporting fixes if the code diverges too much.

**Comment by lordelph** [comment]
I'll see what I can do - might be the weekend before I can devote any time to this. Feel free to add to the PR in the meantime if you're able.

**Comment by jtojnar** [comment]
I probably have a different GD configuration on my computer because all the image comparisons fail for me. Nevertheless, I have managed to fetch the generated image from Travis and now it should finally work.

**Comment by lordelph** [comment]
This is now merged and available as v1.1.0, so if you pull this into composer with a constraint to just use 1.*,  you should be good.

I've merged this into a different branch (php54), and any further backwards compatibility fixes can be made there. GitHub doesn't seem to recognize its merged, so will just close this pull request.

**Pull request closed without merging**
