### PR TITLE
Add test for empty ICO

### PR DESCRIPTION
**Pull request by jtojnar**
It is technically possible for icon not to contain any `ICONDIRENTRY`
structs. In that case, it is still a valid file

    $ identify empty.ico
    empty.ico ICO 0x0 16-bit sRGB 6B 0.000u 0:00.000

but trying to convert it to image will fail with a `TypeError`.

Description of the file format:
https://en.wikipedia.org/wiki/ICO_%28file_format%29#Icon_resource_structure

### CODE REVIEW

**Comment by lordelph** [comment]
Many thanks for this, though I think it would be very rare in the wild!

The unit test fails for this push request 

```
1) Elphin\IcoFileLoader\IcoFileServiceTest::testExtractEmpty
Argument 1 passed to Elphin\IcoFileLoader\IcoFileService::renderImage() must be an instance of Elphin\IcoFileLoader\IconImage, null given, called in /home/travis/build/lordelph/icofileloader/src/IcoFileService.php on line 66 and defined
/home/travis/build/lordelph/icofileloader/src/IcoFileService.php:84
/home/travis/build/lordelph/icofileloader/src/IcoFileService.php:66
/home/travis/build/lordelph/icofileloader/tests/IcoFileServiceTest.php:16
```

If you able to fix the test, I'll merge this. Otherwise, I'll fix it and merge in the next week.

**Comment by jtojnar** [comment]
The tests were only meant to reproduce the issue, I was not sure if returning null is a proper strategy.

**Comment by lordelph** [comment]
Ah I see - then I think it should throw an exception, as previously it would return an image or throw an exception.

**Comment by jtojnar** [comment]
I have chosen a [`DomainException`](https://secure.php.net/manual/en/class.domainexception.php) for the error, since the argument can be a valid file name.

**Pull request merged**
